# Docker Config
export DOCKER_TAG_NAME="temacagent"
export DOCKERFILES_DIR="dockerfiles"

# AppDynamics Controller
export APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1
export APPDYNAMICS_GLOBAL_ACCOUNT_NAME=customer1_XXXXX-XXX-XXXXX-XXXXXX-XXXXXXXX
export APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=XXXXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX
export APPDYNAMICS_CONTROLLER_HOST_NAME=XXXXXX.appdynamics.com
export APPDYNAMICS_SERVERLESS_API_ENDPOINT=https://pdx-sls-agent-api.saas.appdynamics.com
export APPDYNAMICS_CONTROLLER_PORT=8090
export APPDYNAMICS_CONTROLLER_SSL_ENABLED="false"
export APPDYNAMICS_LOG_LEVEL=DEBUG

# Application Name, Tier and Nodes
#export APPDYNAMICS_AGENT_APPLICATION_NAME=DDR_TE_1
#export APPDYNAMICS_AGENT_TIER_NAME=DDR_TE_T1
#export APPDYNAMICS_AGENT_NODE_NAME=DDR_TE_N1
