apiVersion: v1
kind: Service
metadata:
  name: thousandeyes
  namespace: default
spec:
  ports:
  - port: 8080
    name: thousandeyes
  selector:
    app: thousandeyes
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thousandeyes
  namespace: default
spec:
  selector:
    matchLabels:
      app: thousandeyes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: thousandeyes
    spec:
      containers:
        - image: localhost:32000/temacagent
          name: thousandeyes
          env:
          - name: ENV-K8S_V1
            value: "thousandeyes"
          ports:
            - containerPort: 8080
              name: thousandeyes
