apiVersion: v1
kind: Service
metadata:
  name: temacagent
  namespace: default
spec:
  selector:
    name: temacagent
  ports:
  - name: macgent # Actually, no port is needed.
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: temacagent
  labels:
    app: temacagent
  namespace: default
spec:
  hostname: temacagent
  subdomain: default-subdomain
  containers:
    - image: localhost:5555/temacagent
      name: temacagent
